name: cryptopals
version: 0.1.0.0
github: 'manner/cryptopals'
license: BSD3
author: 'Moritz Manner'
copyright: '2020 Moritz Manner'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/cryptopals#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - base64-bytestring
  - base16-bytestring
  - text
  - utf8-string
  - containers

library:
  source-dirs: src

executables:
  cryptopals-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cryptopals

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies:
      - cryptopals
